import { existsSync } from 'node:fs';
import { createRequire } from 'node:module';

import { Document, HeadingLevel, Packer, Paragraph, TextRun } from 'docx';
import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';

import type { DeliveryFormat } from '@allrice/contracts';

export interface GeneratedDeliverable {
  bytes: Buffer;
  extension: string;
  mediaType: string;
}

const formatMetadata: Record<
  DeliveryFormat,
  { extension: string; mediaType: string }
> = {
  markdown: { extension: '.md', mediaType: 'text/markdown' },
  text: { extension: '.txt', mediaType: 'text/plain' },
  html: { extension: '.html', mediaType: 'text/html' },
  json: { extension: '.json', mediaType: 'application/json' },
  docx: {
    extension: '.docx',
    mediaType:
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  },
  xlsx: {
    extension: '.xlsx',
    mediaType:
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  },
  pptx: {
    extension: '.pptx',
    mediaType:
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  },
  pdf: { extension: '.pdf', mediaType: 'application/pdf' },
};

function lines(content: string) {
  return content.replaceAll('\r\n', '\n').split('\n');
}

function plainHeading(line: string) {
  const match = /^(#{1,3})\s+(.+)$/.exec(line.trim());
  return match ? { depth: match[1]!.length, text: match[2]! } : null;
}

async function generateDocx(content: string) {
  const children = lines(content).map((line) => {
    const heading = plainHeading(line);
    if (heading) {
      const levels = [
        HeadingLevel.HEADING_1,
        HeadingLevel.HEADING_2,
        HeadingLevel.HEADING_3,
      ] as const;
      return new Paragraph({
        heading: levels[heading.depth - 1],
        children: [new TextRun(heading.text)],
      });
    }
    return new Paragraph({ children: [new TextRun(line)] });
  });
  return Buffer.from(
    await Packer.toBuffer(
      new Document({
        creator: 'AllRice',
        title: 'AllRice deliverable',
        description: 'Generated by an AllRice AI employee',
        sections: [{ children }],
      }),
    ),
  );
}

function spreadsheetRows(content: string): Record<string, unknown>[] {
  try {
    const parsed = JSON.parse(content) as unknown;
    if (
      Array.isArray(parsed) &&
      parsed.every(
        (value) => value && typeof value === 'object' && !Array.isArray(value),
      )
    ) {
      return parsed as Record<string, unknown>[];
    }
  } catch {
    // Plain text is a supported, deterministic fallback.
  }
  return lines(content).map((value, index) => ({ line: index + 1, value }));
}

async function generateXlsx(content: string) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'AllRice';
  const sheet = workbook.addWorksheet('交付内容');
  const rows = spreadsheetRows(content);
  const columns = Array.from(new Set(rows.flatMap((row) => Object.keys(row))));
  sheet.columns = columns.map((column) => ({
    header: column,
    key: column,
    width: Math.min(60, Math.max(12, column.length + 4)),
  }));
  sheet.addRows(rows);
  sheet.getRow(1).font = { bold: true };
  sheet.views = [{ state: 'frozen', ySplit: 1 }];
  return Buffer.from(await workbook.xlsx.writeBuffer());
}

function presentationSections(content: string) {
  const sections: { title: string; body: string[] }[] = [];
  for (const line of lines(content)) {
    const heading = plainHeading(line);
    if (heading && heading.depth <= 2) {
      sections.push({ title: heading.text, body: [] });
    } else {
      (
        sections.at(-1) ??
        sections[sections.push({ title: '交付内容', body: [] }) - 1]!
      ).body.push(line);
    }
  }
  return sections.length > 0
    ? sections
    : [{ title: '交付内容', body: [content] }];
}

async function generatePptx(content: string) {
  // Use the package's declared CJS entry: tsx's ESM loader otherwise returns
  // a module wrapper here, while compiled Node and Vitest return a constructor.
  const PptxConstructor = createRequire(import.meta.url)(
    'pptxgenjs',
  ) as new () => {
    author: string;
    subject: string;
    layout: string;
    addSlide: () => {
      background: { color: string };
      addText: (text: string, options: Record<string, unknown>) => void;
    };
    write: (options: { outputType: 'nodebuffer' }) => Promise<Buffer>;
  };
  const presentation = new PptxConstructor();
  presentation.author = 'AllRice';
  presentation.subject = 'AI employee deliverable';
  presentation.layout = 'LAYOUT_WIDE';
  for (const section of presentationSections(content).slice(0, 50)) {
    const slide = presentation.addSlide();
    slide.background = { color: 'F7F8FA' };
    slide.addText(section.title, {
      x: 0.7,
      y: 0.45,
      w: 11.9,
      h: 0.65,
      fontFace: 'PingFang SC',
      fontSize: 26,
      bold: true,
      color: '18221C',
      margin: 0,
    });
    slide.addText(section.body.join('\n').slice(0, 5_000), {
      x: 0.75,
      y: 1.35,
      w: 11.75,
      h: 5.5,
      fontFace: 'PingFang SC',
      fontSize: 16,
      color: '344039',
      valign: 'top',
      margin: 0.08,
    });
  }
  return Buffer.from(await presentation.write({ outputType: 'nodebuffer' }));
}

function resolvePdfFont() {
  const configured = process.env.ALLRICE_CJK_FONT_PATH;
  const candidates = [
    configured ? { path: configured, family: undefined } : undefined,
    {
      path: '/System/Library/Fonts/STHeiti Light.ttc',
      family: 'STHeitiSC-Light',
    },
    {
      path: '/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc',
      family: 'NotoSansCJK-Regular',
    },
  ];
  return candidates.find(
    (candidate) => candidate && existsSync(candidate.path),
  );
}

async function generatePdf(content: string) {
  return await new Promise<Buffer>((resolve, reject) => {
    const document = new PDFDocument({
      size: 'A4',
      margins: { top: 54, right: 54, bottom: 54, left: 54 },
      info: { Author: 'AllRice', Title: 'AllRice deliverable' },
    });
    const chunks: Buffer[] = [];
    document.on('data', (chunk: Buffer) => chunks.push(chunk));
    document.on('error', reject);
    document.on('end', () => resolve(Buffer.concat(chunks)));
    const font = resolvePdfFont();
    if (font?.family) document.font(font.path, font.family);
    else if (font) document.font(font.path);
    document.fontSize(11).lineGap(4).text(content, { align: 'left' });
    document.end();
  });
}

export async function generateDeliverable(input: {
  format: DeliveryFormat;
  content: string;
}): Promise<GeneratedDeliverable> {
  const metadata = formatMetadata[input.format];
  let bytes: Buffer;
  if (input.format === 'docx') bytes = await generateDocx(input.content);
  else if (input.format === 'xlsx') bytes = await generateXlsx(input.content);
  else if (input.format === 'pptx') bytes = await generatePptx(input.content);
  else if (input.format === 'pdf') bytes = await generatePdf(input.content);
  else bytes = Buffer.from(input.content, 'utf8');
  return { bytes, ...metadata };
}
